### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

Hey! Thank you so much for this! It's super cool!

I've made a few changes to incorporate some best practices. Feel free to push back / ask more about it.

### processEventBatch

We're deprecating this with the new release that's coming out today, so I moved this plugin to a new approach using `onEvent`. `onEvent` is used for plugins that need to read the event but don't modify it, as is the case here. Docs for this are coming out today.

### statusOk

The current checking mechanism would only match a 200, in which case it could just check if the status is equal to 200. To check for all 2xx codes, I've added in `statusOk`. Other plugins use this as well.

## Suggestions

I haven't tried this out myself but I'm happy to get it in and iterate from there. A few things I'd suggest, but that are not necessary at this stage:

### Additional config verification

I'd check `config.eventMethodType` for example. In fact, a better choice might be to use the `choice` type with options like 'POST' and 'PUT', or whatever should be allowed. You could also check for leading slashes on the event path etc. Essentially anything that would cause an error to be thrown during `onEvent` rather than `setupPlugin`.

### Tests

These are always nice :D

### Retry queue for failed requests

This is something that recent developments in the plugin server allow for. I'm supposed to implement a few plugins using retry queues this cycle so you could use those as an example to implement it here too. You couldn't have known this was possible yet though because the docs are also coming later today.

## Questions

Do you not want to send event names to Salesforce?

### CODE REVIEW

**Review by ConradKurth — APPROVED** [review]
I like all these changes! And yeah interesting usage there for the statusok, Although I do still think the way I had it still works due to the rounding of integers, BUT regardless i like DRY'ing up that check

**Comment by ConradKurth** [comment]
@yakkomajuri I do like your suggestions and I will make some issues for me to do (or anyone). I appreciate you taking the time to look at this and improve it!

**Comment by ConradKurth** [comment]
#5 #4 https://github.com/Vinovest/posthog-salesforce/issues/3

**Comment by yakkomajuri** [comment]
@ConradKurth unfortunately no such thing as an integer in JS (and consequently in TS).


Screenshot 2021-05-13 at 16 30 23

**Comment by yakkomajuri** [comment]
Just mentioned this in Slack but another thing we should do before making this available on Cloud is certifying that `salesforceHost` is indeed a Salesforce URL.

**Comment by ConradKurth** [comment]
@yakkomajuri done!

**Pull request merged**
